version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: delivery_soft_db
    ports:
      - '5432:5432'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/data/postgres
volumes:
  postgres-db:
    driver: local